title: nezha-agent
frequency: 3
dirfilter:
- tmp
- .git
- .github
- scripts
- vendor
- logs
- .github
ext:
- go
- js
- tmpl
- ini
- html
enablerun: true
action:
  before:
  - find . -path vendor -prune -name ".DS_Store" -print -delete
  - go mod tidy && go mod vendor
  after:
  - ps -ef|grep 'nezha-agent'| grep -v grep | grep -v git | awk '{print $2}' | xargs kill -9 
  - #./nezha-agent -d -s 127.0.0.1:5222 -p yuuYWQEIRPw5vqa7jp &
  - echo "start nezha-agent"
  exit:
  - ps -ef|grep 'nezha-agent'| grep -v grep | grep -v git | awk '{print $2}' | xargs kill -9
  - echo "stop nezha-agent"